"""add vocabulary tables

Revision ID: 7d3d9fd98f1e
Revises: f23e88fd2614
Create Date: 2026-07-17 17:45:22.190406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3d9fd98f1e'
down_revision: Union[str, Sequence[str], None] = 'f23e88fd2614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('ipa', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('DICTIONARY_API', 'LLM', name='vocabulary_cache_source'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'language_id', name='uq_vocabulary_cache_word_language')
    )
    op.create_index('ix_vocabulary_cache_language_id', 'vocabulary_cache', ['language_id'], unique=False)
    op.create_table('vocabulary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('ipa', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('srs_stage', sa.Integer(), nullable=False),
    sa.Column('srs_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('srs_stage >= 0', name='ck_vocabulary_entries_srs_stage_non_negative'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocabulary_entries_srs_due_at', 'vocabulary_entries', ['srs_due_at'], unique=False)
    op.create_index('ix_vocabulary_entries_user_language', 'vocabulary_entries', ['user_id', 'language_id'], unique=False)
    op.create_table('vocabulary_review_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vocabulary_entry_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_entry_id'], ['vocabulary_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocabulary_review_log_user_id', 'vocabulary_review_log', ['user_id'], unique=False)
    op.create_index('ix_vocabulary_review_log_vocabulary_entry_id', 'vocabulary_review_log', ['vocabulary_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vocabulary_review_log_vocabulary_entry_id', table_name='vocabulary_review_log')
    op.drop_index('ix_vocabulary_review_log_user_id', table_name='vocabulary_review_log')
    op.drop_table('vocabulary_review_log')
    op.drop_index('ix_vocabulary_entries_user_language', table_name='vocabulary_entries')
    op.drop_index('ix_vocabulary_entries_srs_due_at', table_name='vocabulary_entries')
    op.drop_table('vocabulary_entries')
    op.drop_index('ix_vocabulary_cache_language_id', table_name='vocabulary_cache')
    op.drop_table('vocabulary_cache')
    # ### end Alembic commands ###
