"""add dictionary tables

Revision ID: a42e4c358c80
Revises: 7d3d9fd98f1e
Create Date: 2026-07-18 10:55:18.135641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a42e4c358c80'
down_revision: Union[str, Sequence[str], None] = '7d3d9fd98f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'language', name='uq_dictionary_word_language')
    )
    op.create_index(op.f('ix_dictionary_entries_language'), 'dictionary_entries', ['language'], unique=False)
    op.create_index(op.f('ix_dictionary_entries_word'), 'dictionary_entries', ['word'], unique=False)
    op.create_index('ix_dictionary_word_language', 'dictionary_entries', ['word', 'language'], unique=False)
    op.create_table('dictionary_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('script', sa.String(length=30), nullable=False),
    sa.Column('reading', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['dictionary_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_readings_entry_id'), 'dictionary_readings', ['entry_id'], unique=False)
    op.create_table('dictionary_senses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=False),
    sa.Column('definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['dictionary_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_senses_entry_id'), 'dictionary_senses', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictionary_senses_entry_id'), table_name='dictionary_senses')
    op.drop_table('dictionary_senses')
    op.drop_index(op.f('ix_dictionary_readings_entry_id'), table_name='dictionary_readings')
    op.drop_table('dictionary_readings')
    op.drop_index('ix_dictionary_word_language', table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_word'), table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_language'), table_name='dictionary_entries')
    op.drop_table('dictionary_entries')
    # ### end Alembic commands ###
